import type { PdfTemplateDefinition } from '@/lib/pdf/engine/templates/types';

const base = (
  id: string,
  name: string,
  description: string,
  inspiration: string,
  theme: PdfTemplateDefinition['theme'],
  overrides: Partial<PdfTemplateDefinition> = {},
): PdfTemplateDefinition => ({
  id,
  name,
  description,
  inspiration,
  theme,
  layout: 'classic',
  logoPosition: 'left',
  headerStyle: 'default',
  tableStyle: 'default',
  totalsStyle: 'default',
  showPartyCards: true,
  titleAlign: 'right',
  fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', Helvetica, Arial, sans-serif",
  ...overrides,
});

export const PDF_TEMPLATES: PdfTemplateDefinition[] = [
  base(
    'classic-blue',
    'Classique Bleu',
    'Modèle équilibré et professionnel',
    'Factume',
    { primary: '#2563EB', accent: '#1D4ED8', text: '#111827', muted: '#6B7280', border: '#E5E7EB', surface: '#F9FAFB', surfaceAlt: '#FFFFFF', paymentBg: '#EFF6FF', paymentBorder: '#BFDBFE' },
  ),
  base(
    'pennylane-clean',
    'Pennylane Clean',
    'Épuré avec bandeau coloré',
    'Pennylane',
    { primary: '#00B386', accent: '#008F6C', text: '#1A1F36', muted: '#697386', border: '#E3E8EE', surface: '#F6F9FC', surfaceAlt: '#FFFFFF', paymentBg: '#E6FAF4', paymentBorder: '#99E6D0' },
    { layout: 'banner', headerStyle: 'band', tableStyle: 'striped', totalsStyle: 'highlight' },
  ),
  base(
    'indy-modern',
    'Indy Moderne',
    'Typographie aérée, totaux mis en avant',
    'Indy',
    { primary: '#5B4FFF', accent: '#4338CA', text: '#0F172A', muted: '#64748B', border: '#E2E8F0', surface: '#F8FAFC', surfaceAlt: '#FFFFFF', paymentBg: '#EEF2FF', paymentBorder: '#C7D2FE' },
    { layout: 'minimal', headerStyle: 'underline', totalsStyle: 'accent', tableStyle: 'minimal' },
  ),
  base(
    'henrri-minimal',
    'Henrri Minimal',
    'Ultra sobre, focus sur le contenu',
    'Henrri',
    { primary: '#18181B', accent: '#3F3F46', text: '#18181B', muted: '#71717A', border: '#E4E4E7', surface: '#FAFAFA', surfaceAlt: '#FFFFFF', paymentBg: '#F4F4F5', paymentBorder: '#D4D4D8' },
    { layout: 'minimal', showPartyCards: false, tableStyle: 'minimal', totalsStyle: 'boxed', headerStyle: 'underline' },
  ),
  base(
    'quickbooks-pro',
    'QuickBooks Pro',
    'Structure classique comptable',
    'QuickBooks',
    { primary: '#2CA01C', accent: '#1E7A12', text: '#1B1B1B', muted: '#6B6B6B', border: '#D9D9D9', surface: '#F5F5F5', surfaceAlt: '#FFFFFF', paymentBg: '#E8F5E6', paymentBorder: '#A8D5A2' },
    { layout: 'classic', tableStyle: 'bordered', totalsStyle: 'boxed', headerStyle: 'boxed' },
  ),
  base(
    'stripe-sleek',
    'Stripe Sleek',
    'Design tech premium sombre',
    'Stripe Invoicing',
    { primary: '#635BFF', accent: '#0A2540', text: '#0A2540', muted: '#425466', border: '#E6EBF1', surface: '#F6F9FC', surfaceAlt: '#FFFFFF', paymentBg: '#F0EDFF', paymentBorder: '#C4BBFF' },
    { layout: 'stripe', headerStyle: 'band', totalsStyle: 'accent', logoPosition: 'left' },
  ),
  base(
    'freebe-fresh',
    'Freebe Fresh',
    'Couleurs vives et dynamiques',
    'Freebe',
    { primary: '#FF6B35', accent: '#E85D2C', text: '#2D3142', muted: '#6C757D', border: '#E9ECEF', surface: '#FFF8F5', surfaceAlt: '#FFFFFF', paymentBg: '#FFF0EB', paymentBorder: '#FFCDB8' },
    { layout: 'banner', headerStyle: 'band', totalsStyle: 'highlight', titleAlign: 'center' },
  ),
  base(
    'navy-corporate',
    'Navy Corporate',
    'Sérieux et institutionnel',
    'Corporate',
    { primary: '#1E3A5F', accent: '#0F2744', text: '#1A1A2E', muted: '#5C6B7A', border: '#D1D9E0', surface: '#F0F4F8', surfaceAlt: '#FFFFFF', paymentBg: '#E8EEF4', paymentBorder: '#A8BDD0' },
    { layout: 'split', headerStyle: 'boxed', tableStyle: 'bordered' },
  ),
  base(
    'emerald-finance',
    'Emerald Finance',
    'Vert finance, totaux encadrés',
    'Finance',
    { primary: '#059669', accent: '#047857', text: '#064E3B', muted: '#6B7280', border: '#D1FAE5', surface: '#ECFDF5', surfaceAlt: '#FFFFFF', paymentBg: '#D1FAE5', paymentBorder: '#6EE7B7' },
    { totalsStyle: 'boxed', tableStyle: 'striped' },
  ),
  base(
    'slate-professional',
    'Slate Professional',
    'Gris ardoise élégant',
    'Professional',
    { primary: '#475569', accent: '#334155', text: '#0F172A', muted: '#94A3B8', border: '#E2E8F0', surface: '#F1F5F9', surfaceAlt: '#FFFFFF', paymentBg: '#F1F5F9', paymentBorder: '#CBD5E1' },
    { layout: 'card', showPartyCards: true, tableStyle: 'striped' },
  ),
  base(
    'warm-amber',
    'Warm Amber',
    'Tons chauds artisanaux',
    'Artisan',
    { primary: '#D97706', accent: '#B45309', text: '#292524', muted: '#78716C', border: '#FDE68A', surface: '#FFFBEB', surfaceAlt: '#FFFFFF', paymentBg: '#FEF3C7', paymentBorder: '#FCD34D' },
    { layout: 'centered', logoPosition: 'center', titleAlign: 'center' },
  ),
  base(
    'rose-elegant',
    'Rose Élégant',
    'Raffiné avec touches roses',
    'Luxe',
    { primary: '#BE185D', accent: '#9D174D', text: '#1F2937', muted: '#9CA3AF', border: '#FBCFE8', surface: '#FDF2F8', surfaceAlt: '#FFFFFF', paymentBg: '#FCE7F3', paymentBorder: '#F9A8D4' },
    { layout: 'card', headerStyle: 'underline', totalsStyle: 'highlight' },
  ),
  base(
    'teal-modern',
    'Teal Modern',
    'Bleu-vert contemporain',
    'Modern',
    { primary: '#0D9488', accent: '#0F766E', text: '#134E4A', muted: '#6B7280', border: '#CCFBF1', surface: '#F0FDFA', surfaceAlt: '#FFFFFF', paymentBg: '#CCFBF1', paymentBorder: '#5EEAD4' },
    { layout: 'sidebar', totalsStyle: 'accent' },
  ),
  base(
    'charcoal-bold',
    'Charcoal Bold',
    'Contraste fort, en-tête bandeau',
    'Bold',
    { primary: '#1F2937', accent: '#111827', text: '#111827', muted: '#6B7280', border: '#374151', surface: '#F3F4F6', surfaceAlt: '#FFFFFF', paymentBg: '#E5E7EB', paymentBorder: '#9CA3AF' },
    { layout: 'banner', headerStyle: 'band', tableStyle: 'bordered', totalsStyle: 'boxed' },
  ),
  base(
    'sky-open',
    'Sky Open',
    'Lumineux et aéré',
    'Open',
    { primary: '#0284C7', accent: '#0369A1', text: '#0C4A6E', muted: '#64748B', border: '#BAE6FD', surface: '#F0F9FF', surfaceAlt: '#FFFFFF', paymentBg: '#E0F2FE', paymentBorder: '#7DD3FC' },
    { layout: 'minimal', showPartyCards: true, tableStyle: 'minimal' },
  ),
  base(
    'purple-creative',
    'Purple Creative',
    'Créatif avec logo centré',
    'Creative',
    { primary: '#7C3AED', accent: '#6D28D9', text: '#1E1B4B', muted: '#8B5CF6', border: '#DDD6FE', surface: '#F5F3FF', surfaceAlt: '#FFFFFF', paymentBg: '#EDE9FE', paymentBorder: '#C4B5FD' },
    { layout: 'centered', logoPosition: 'center', titleAlign: 'center', totalsStyle: 'accent' },
  ),
  base(
    'coral-vibrant',
    'Coral Vibrant',
    'Énergique et mémorable',
    'Vibrant',
    { primary: '#F43F5E', accent: '#E11D48', text: '#1C1917', muted: '#78716C', border: '#FECDD3', surface: '#FFF1F2', surfaceAlt: '#FFFFFF', paymentBg: '#FFE4E6', paymentBorder: '#FDA4AF' },
    { layout: 'banner', headerStyle: 'band', tableStyle: 'striped' },
  ),
  base(
    'forest-organic',
    'Forest Organic',
    'Naturel et apaisant',
    'Organic',
    { primary: '#166534', accent: '#14532D', text: '#14532D', muted: '#6B7280', border: '#BBF7D0', surface: '#F0FDF4', surfaceAlt: '#FFFFFF', paymentBg: '#DCFCE7', paymentBorder: '#86EFAC' },
    { layout: 'classic', tableStyle: 'striped', headerStyle: 'underline' },
  ),
  base(
    'midnight-premium',
    'Midnight Premium',
    'Haut de gamme, bandeau sombre',
    'Premium',
    { primary: '#312E81', accent: '#1E1B4B', text: '#1E1B4B', muted: '#6366F1', border: '#C7D2FE', surface: '#EEF2FF', surfaceAlt: '#FFFFFF', paymentBg: '#E0E7FF', paymentBorder: '#A5B4FC' },
    { layout: 'stripe', headerStyle: 'band', totalsStyle: 'highlight', logoPosition: 'right' },
  ),
  base(
    'sandstone-classic',
    'Sandstone Classic',
    'Beige classique et intemporel',
    'Classic',
    { primary: '#92400E', accent: '#78350F', text: '#44403C', muted: '#A8A29E', border: '#E7E5E4', surface: '#FAFAF9', surfaceAlt: '#FFFFFF', paymentBg: '#F5F5F4', paymentBorder: '#D6D3D1' },
    { layout: 'split', tableStyle: 'bordered', totalsStyle: 'boxed' },
  ),
  base(
    'graphite-tech',
    'Graphite Tech',
    'Tech sobre, tableau minimal',
    'Tech',
    { primary: '#374151', accent: '#1F2937', text: '#111827', muted: '#9CA3AF', border: '#E5E7EB', surface: '#F9FAFB', surfaceAlt: '#FFFFFF', paymentBg: '#F3F4F6', paymentBorder: '#D1D5DB' },
    { layout: 'minimal', tableStyle: 'minimal', showPartyCards: false, headerStyle: 'underline' },
  ),
];

export const PDF_TEMPLATE_MAP = new Map(PDF_TEMPLATES.map((t) => [t.id, t]));

export function resolvePdfTemplate(templateId?: string | null): PdfTemplateDefinition {
  if (templateId && PDF_TEMPLATE_MAP.has(templateId)) {
    return PDF_TEMPLATE_MAP.get(templateId)!;
  }

  return PDF_TEMPLATE_MAP.get('classic-blue')!;
}
